// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: demoapi.proto

package demoapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FullName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GivenName     string                 `protobuf:"bytes,1,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyName    string                 `protobuf:"bytes,2,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullName) Reset() {
	*x = FullName{}
	mi := &file_demoapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullName) ProtoMessage() {}

func (x *FullName) ProtoReflect() protoreflect.Message {
	mi := &file_demoapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullName.ProtoReflect.Descriptor instead.
func (*FullName) Descriptor() ([]byte, []int) {
	return file_demoapi_proto_rawDescGZIP(), []int{0}
}

func (x *FullName) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *FullName) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

type EchoData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	FullName      *FullName              `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Emails        []string               `protobuf:"bytes,4,rep,name=emails,proto3" json:"emails,omitempty"`
	Description   *string                `protobuf:"bytes,10,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoData) Reset() {
	*x = EchoData{}
	mi := &file_demoapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoData) ProtoMessage() {}

func (x *EchoData) ProtoReflect() protoreflect.Message {
	mi := &file_demoapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoData.ProtoReflect.Descriptor instead.
func (*EchoData) Descriptor() ([]byte, []int) {
	return file_demoapi_proto_rawDescGZIP(), []int{1}
}

func (x *EchoData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EchoData) GetFullName() *FullName {
	if x != nil {
		return x.FullName
	}
	return nil
}

func (x *EchoData) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *EchoData) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_demoapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demoapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_demoapi_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connected     bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_demoapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demoapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_demoapi_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

var File_demoapi_proto protoreflect.FileDescriptor

const file_demoapi_proto_rawDesc = "" +
	"\n" +
	"\rdemoapi.proto\x12\x12demo.service.proto\"J\n" +
	"\bFullName\x12\x1d\n" +
	"\n" +
	"given_name\x18\x01 \x01(\tR\tgivenName\x12\x1f\n" +
	"\vfamily_name\x18\x02 \x01(\tR\n" +
	"familyName\"\xbe\x01\n" +
	"\bEchoData\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x129\n" +
	"\tfull_name\x18\x03 \x01(\v2\x1c.demo.service.proto.FullNameR\bfullName\x12\x16\n" +
	"\x06emails\x18\x04 \x03(\tR\x06emails\x12%\n" +
	"\vdescription\x18\n" +
	" \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"-\n" +
	"\rLoginResponse\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected2\x9f\x01\n" +
	"\vDemoService\x12B\n" +
	"\x04Echo\x12\x1c.demo.service.proto.EchoData\x1a\x1c.demo.service.proto.EchoData\x12L\n" +
	"\x05Login\x12 .demo.service.proto.LoginRequest\x1a!.demo.service.proto.LoginResponseB\fZ\n" +
	"./;demoapib\x06proto3"

var (
	file_demoapi_proto_rawDescOnce sync.Once
	file_demoapi_proto_rawDescData []byte
)

func file_demoapi_proto_rawDescGZIP() []byte {
	file_demoapi_proto_rawDescOnce.Do(func() {
		file_demoapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demoapi_proto_rawDesc), len(file_demoapi_proto_rawDesc)))
	})
	return file_demoapi_proto_rawDescData
}

var file_demoapi_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_demoapi_proto_goTypes = []any{
	(*FullName)(nil),      // 0: demo.service.proto.FullName
	(*EchoData)(nil),      // 1: demo.service.proto.EchoData
	(*LoginRequest)(nil),  // 2: demo.service.proto.LoginRequest
	(*LoginResponse)(nil), // 3: demo.service.proto.LoginResponse
}
var file_demoapi_proto_depIdxs = []int32{
	0, // 0: demo.service.proto.EchoData.full_name:type_name -> demo.service.proto.FullName
	1, // 1: demo.service.proto.DemoService.Echo:input_type -> demo.service.proto.EchoData
	2, // 2: demo.service.proto.DemoService.Login:input_type -> demo.service.proto.LoginRequest
	1, // 3: demo.service.proto.DemoService.Echo:output_type -> demo.service.proto.EchoData
	3, // 4: demo.service.proto.DemoService.Login:output_type -> demo.service.proto.LoginResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_demoapi_proto_init() }
func file_demoapi_proto_init() {
	if File_demoapi_proto != nil {
		return
	}
	file_demoapi_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demoapi_proto_rawDesc), len(file_demoapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demoapi_proto_goTypes,
		DependencyIndexes: file_demoapi_proto_depIdxs,
		MessageInfos:      file_demoapi_proto_msgTypes,
	}.Build()
	File_demoapi_proto = out.File
	file_demoapi_proto_goTypes = nil
	file_demoapi_proto_depIdxs = nil
}
